name: Run
on:
  push:
  schedule:
    - cron: '0 * * * *'

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run
        run: node index.js