name: Run
on:
  push:
  schedule:
    - cron: '0 * * * *'

env:
  BLIZZ_CLIENT_ID: ${{ secrets.BLIZZ_CLIENT_ID }}
  BLIZZ_CLIENT_SECRET: ${{ secrets.BLIZZ_CLIENT_SECRET }}

  DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
  DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run
        run: npm run start